# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base_gs
  - /dataset: nerf
  - /initialization: point_cloud
  - /render: 3dgrt
  - _self_

# overwrite of default parameters
val_frequency: 999999 # never validate
